# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: Copyright contributors to the vLLM project
default_stages:
  - pre-commit  # Run locally
  - manual  # Run in CI
exclude: ^(codecheck_toolkits/)
repos:
- repo: local
  hooks:
    - id: pre-run-shell
      name: "Pre-run: copy codecheck_toolkits/pyproject.toml to ./"
      entry: ln -s codecheck_toolkits/pyproject.toml pyproject.toml
      language: system
      always_run: true
      pass_filenames: false
    - id: pre-config-markdownlint
      name: "Pre-run: copy codecheck_toolkits/.markdownlint.yaml to ./"
      entry: ln -s codecheck_toolkits/.markdownlint.yaml .markdownlint.yaml
      language: system
      always_run: true
      pass_filenames: false
      stages: [ manual ]
    - id: pre-config-shellcheck
      name: "Pre-run: copy codecheck_toolkits/.shellcheckrc to ./"
      entry: ln -s codecheck_toolkits/.shellcheckrc .shellcheckrc
      language: system
      always_run: true
      pass_filenames: false
- repo: https://gitee.com/moran3/yapf
  rev: v0.43.0
  hooks:
  - id: yapf
    args: [--in-place, --verbose]
    # Keep the same list from yapfignore here to avoid yapf failing without any inputs
    exclude: '(.buildkite|benchmarks|build|examples)/.*'
    stages: [pre-commit] # Don't run in CI
  - id: yapf
    args: [--diff]
    # Keep the same list from yapfignore here to avoid yapf failing without any inputs
    exclude: '(.buildkite|benchmarks|build|examples)/.*'
    stages: [manual] # run in CI
- repo: https://gitee.com/moran3/ruff-pre-commit
  rev: v0.11.7
  hooks:
  - id: ruff
    args: [--output-format, github, --fix]
    stages: [pre-commit] # Don't run in CI
  - id: ruff
    args: ['--exit-non-zero-on-fix']
    stages: [manual] # run in CI
  - id: ruff-format
    files: ^(.buildkite|benchmarks|examples)/.*
    stages: [pre-commit] # Don't run in CI
  - id: ruff-format
    args: ['--diff']
    files: ^(.buildkite|benchmarks|examples)/.*
    stages: [manual] # run in CI
- repo: https://gitee.com/moran3/typos
  rev: v1.35.5
  hooks:
  - id: typos
    args: [ -v ]
- repo: https://gitee.com/moran3/isort
  rev: 6.0.1
  hooks:
  - id: isort
    exclude: ^(examples/|tests/|vllm_mindspore/__init__.py)
    stages: [pre-commit]
  - id: isort
    exclude: ^(examples/|tests/|vllm_mindspore/__init__.py)
    args: ['--check-only', '--diff']
    stages: [ manual ]
- repo: https://gitee.com/moran3/mirrors-clang-format
  rev: v20.1.3
  hooks:
  - id: clang-format
    exclude: 'csrc/(moe/topk_softmax_kernels.cu|quantization/gguf/(ggml-common.h|dequantize.cuh|vecdotq.cuh|mmq.cuh|mmvq.cuh))|vllm/third_party/.*'
    types_or: [c++, cuda]
    args: [--style=file, --verbose]
#  Node.js in CI machine is too old to support it.
#- repo: https://gitee.com/moran3/markdownlint-cli
#  rev: v0.45.0
#  hooks:
#  - id: markdownlint
#    exclude: '.*\.inc\.md|\.gitee/'
#    stages: [manual] # Only run in CI
- repo: https://gitee.com/moran3/uv-pre-commit
  rev: 0.6.17
  hooks:
    - id: pip-compile
      args: [requirements/test.in, -o, requirements/test.txt, --index-strategy, unsafe-best-match, --torch-backend, cu128, --python-platform, x86_64-manylinux_2_28]
      files: ^requirements/test\.(in|txt)$
- repo: local
  hooks:
  - id: mypy-local
    name: Run mypy for local Python installation
    entry: python codecheck_toolkits/pre_commit/mypy.py 0 "local"
    stages: [pre-commit] # Don't run in CI
    <<: &mypy_common
      language: python
      types_or: [python, pyi]
      require_serial: true
      additional_dependencies: [mypy==1.11.1, regex, types-cachetools, types-setuptools, types-PyYAML, types-requests, types-torch, pydantic]
  - id: mypy-3.10 # TODO: Use https://gitee.com/pre-commit/mirrors-mypy when mypy setup is less awkward
    name: Run mypy for Python 3.10
    entry: python codecheck_toolkits/pre_commit/mypy.py 1 "3.10"
    <<: *mypy_common
    stages: [manual] # Only run in CI
  - id: mypy-3.11 # TODO: Use https://gitee.com/pre-commit/mirrors-mypy when mypy setup is less awkward
    name: Run mypy for Python 3.11
    entry: python codecheck_toolkits/pre_commit/mypy.py 1 "3.11"
    <<: *mypy_common
    stages: [manual] # Only run in CI
  - id: mypy-3.12 # TODO: Use https://gitee.com/pre-commit/mirrors-mypy when mypy setup is less awkward
    name: Run mypy for Python 3.12
    entry: python codecheck_toolkits/pre_commit/mypy.py 1 "3.12"
    <<: *mypy_common
    stages: [manual] # Only run in CI
  - id: shellcheck
    name: Lint shell scripts
    entry: codecheck_toolkits/shellcheck.sh
    language: script
    types: [shell]
  - id: png-lint
    name: Lint PNG exports from excalidraw
    entry: codecheck_toolkits/png-lint.sh
    language: script
    types: [png]
  - id: signoff-commit
    name: Sign-off Commit
    entry: bash
    args:
      - -c
      - |
        if ! grep -q "^Signed-off-by: $(git config user.name) <$(git config user.email)>" "$(git rev-parse --git-path COMMIT_EDITMSG)"; then
          printf "\nSigned-off-by: $(git config user.name) <$(git config user.email)>\n" >> "$(git rev-parse --git-path COMMIT_EDITMSG)"
        fi
    language: system
    verbose: true
    stages: [commit-msg]
  - id: check-spdx-header
    name: Check SPDX headers
    entry: python codecheck_toolkits/check_spdx_header.py
    language: python
    types: [python]
#  - id: check-root-lazy-imports
#    name: Check root lazy imports
#    entry: python codecheck_toolkits/check_init_lazy_imports.py
#    language: python
#    types: [python]
  - id: check-filenames
    name: Check for spaces in all filenames
    entry: bash
    args:
      - -c
      - 'git ls-files | grep " " && echo "Filenames should not contain spaces!" && exit 1 || exit 0'
    language: system
    always_run: true
    pass_filenames: false
  - id: update-dockerfile-graph
    name: Update Dockerfile dependency graph
    entry: codecheck_toolkits/update-dockerfile-graph.sh
    language: script
  - id: enforce-import-regex-instead-of-re
    name: Enforce import regex as re
    entry: python codecheck_toolkits/enforce_regex_import.py
    language: python
    types: [python]
    pass_filenames: false
    additional_dependencies: [regex]
  # forbid directly import triton
  - id: forbid-direct-triton-import
    name: "Forbid direct 'import triton'"
    entry: python codecheck_toolkits/check_triton_import.py
    language: python
    types: [python]
    pass_filenames: false
    additional_dependencies: [regex]
  - id: check-pickle-imports
    name: Prevent new pickle/cloudpickle imports
    entry: python codecheck_toolkits/pre_commit/check_pickle_imports.py
    language: python
    types: [python]
    additional_dependencies: [regex]
  - id: validate-config
    name: Validate configuration has default values and that each field has a docstring
    entry: python codecheck_toolkits/validate_config.py
    language: python
    additional_dependencies: [regex]
  # remove cache files
  - id: remove cache
    name: "remove ruff, mypy, shellcheck cache"
    entry: rm -rf .ruff_cache/ .mypy_cache/ shellcheck-stable/
    language: system
    always_run: true
    pass_filenames: false
  # Keep `suggestion` last
  - id: suggestion
    name: Suggestion
    entry: bash -c 'echo "To bypass all the pre-commit hooks, add --no-verify to git commit. To skip a specific hook, prefix the commit command with SKIP=<hook-id>."'
    language: system
    verbose: true
    pass_filenames: false
  # Insert new entries above the `suggestion` entry
  - id: post-run-shell
    name: "Post-run: remove ./pyproject.toml"
    entry: rm -f pyproject.toml
    language: system
    always_run: true
    pass_filenames: false
  - id: post-config-markdownlint
    name: "Post-run: remove ./.markdownlint.yaml"
    entry: rm -f .markdownlint.yaml
    language: system
    always_run: true
    pass_filenames: false
    stages: [ manual ]
  - id: post-config-shellcheck
    name: "Post-run: remove ./.shellcheckrc"
    entry: rm -f .shellcheckrc
    language: system
    always_run: true
    pass_filenames: false
  # Insert new entries above the `suggestion` entry
