/**
 * Copyright 2025 Huawei Technologies Co., Ltd
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#ifndef MRT_DIALECT_MRT_OPS_DIALECT_H
#define MRT_DIALECT_MRT_OPS_DIALECT_H

#include "mlir/IR/Dialect.h"
#include "mlir/IR/DialectImplementation.h"
#include "mlir/IR/Types.h"

// Include the generated dialect header
#include "mopt/Dialect/Mrt/MrtDialect.h.inc"

namespace mrt {

// Additional dialect methods can be added here if needed
// The main dialect class is generated by TableGen

}  // namespace mrt

#endif  // MRT_DIALECT_MRT_OPS_DIALECT_H
