# =========================================================================
# LLVM Source Download (no build)
# =========================================================================
# This file builds and installs LLVM/MLIR with mrt_add_pkg and
# records the relevant paths for later stages.
# =========================================================================

message(STATUS "========================================")
message(STATUS "Preparing LLVM build")
message(STATUS "========================================")

set(TOP_DIR "${CMAKE_CURRENT_LIST_DIR}/..")

if(NOT COMMAND mrt_add_pkg)
    include(${CMAKE_CURRENT_LIST_DIR}/utils.cmake)
endif()

set(LLVM_VERSION "2025.10.28" CACHE INTERNAL "LLVM daily version")
set(LLVM_COMMIT "41f65666f6378bba7266be7c662c70074f04ed75" CACHE INTERNAL "LLVM commit hash")
set(LLVM_SHA256 "c69994a402c480c64ba8b266a5c2a00a7216a2ad5b6f40b5c6cb5cece15c0f94")
set(LLVM_URL "https://gitee.com/mirrors/LLVM/repository/archive/${LLVM_COMMIT}.zip")

set(LLVM_CMAKE_OPTIONS
    -DCMAKE_BUILD_TYPE=Release
    -DPython3_FIND_VIRTUALENV=ONLY
    -DPython_FIND_VIRTUALENV=ONLY
    -DLLVM_ENABLE_PROJECTS=mlir
    -DLLVM_TARGETS_TO_BUILD=host
    -DMLIR_ENABLE_BINDINGS_PYTHON=ON
    -DLLVM_INSTALL_UTILS=ON
)

mrt_add_pkg(llvm_project
    VER ${LLVM_VERSION}
    URL ${LLVM_URL}
    SHA256 ${LLVM_SHA256}
    CMAKE_PATH llvm
    CMAKE_OPTION ${LLVM_CMAKE_OPTIONS}
    CUSTOM_CMAKE_GENERATOR Ninja
    PATCHES ${TOP_DIR}/third_party/patch/llvm/001-install-pdll-files.patch
)

# Build directory is inside source directory
# Since llvm_project path already includes compiler flags and version info,
# the build directory will automatically be unique for different source configurations
set(LLVM_BUILD_DIR "${llvm_project_DIRPATH}")

message(STATUS "LLVM build directory: ${LLVM_BUILD_DIR}")

set(ENV_FILE "${CMAKE_CURRENT_BINARY_DIR}/set_env.sh")
file(WRITE ${ENV_FILE} "# Auto-generated by cmake/llvm.cmake\n")
file(APPEND ${ENV_FILE} "export LLVM_BUILD_DIR=\"${LLVM_BUILD_DIR}\"\n")
file(APPEND ${ENV_FILE} "export LLVM_DIR=\"${LLVM_BUILD_DIR}/lib/cmake/llvm\"\n")
file(APPEND ${ENV_FILE} "export MLIR_DIR=\"${LLVM_BUILD_DIR}/lib/cmake/mlir\"\n")
