# Copyright 2025 Huawei Technologies Co., Ltd
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Utility functions for loading ops definitions from JSON files."""

import json
import os
import glob
from typing import Dict, List, Any


def _parse_ops_def(json_data: Dict[str, Any]) -> List[Dict[str, Any]]:
    """Parse the operation definitions from the JSON data."""
    ret = []
    for op in json_data['!instanceof']['Op']:
        ori_op_def = json_data[op]
        # Skip generate
        if ori_op_def['generated'] == 0:
            continue
        # Currently, only the opName, arguments, and results are needed.
        op_def = {
            'opName': ori_op_def['opName'],
            'arguments': ori_op_def['arguments'],
            'results': ori_op_def['results'],
        }
        ret.append(op_def)
    return ret

def load_ops_def_from_json_file(json_file_path: str) -> List[Dict[str, Any]]:
    """
    Load the json file which is generated by llvm-tblgen and extract the operation definitions from it.

    Args:
        json_file_path: Path to the JSON file.

    Returns:
        List of dictionaries, each dictionary is an operation definition.
    """
    print(f"Loading the JSON file: {json_file_path}")
    if not os.path.exists(json_file_path):
        raise FileNotFoundError(f"JSON file not found: {json_file_path},\
        make sure you have run the llvm-tblgen to generate the JSON file.")

    with open(json_file_path, 'r', encoding='utf-8') as f:
        json_data = json.load(f)

    # Dump the JSON data as a readable JSON file for debugging and verification
    # Rewrite the original JSON file with a readable format (with indentation)
    with open(json_file_path, "w", encoding="utf-8") as f:
        json.dump(json_data, f, ensure_ascii=False, indent=4)
    print(f"Dumped readable Mrt Dialect JSON to: {json_file_path}")

    ops_def = _parse_ops_def(json_data)
    return ops_def

def load_ops_def_from_json_files(json_file_dir: str) -> List[List[Dict[str, Any]]]:
    """
    Load ops def from multiple json files.

    Args:
        json_file_dir: Directory path to the json files.

    Returns:
        List of lists, each list is a set of operation definitions.
    """
    ret = []
    json_file_paths = glob.glob(os.path.join(json_file_dir, '*.json'))
    if not json_file_paths:
        raise FileNotFoundError(f"No json files found in directory: {json_file_dir}")
    for json_file_path in json_file_paths:
        ret.append(load_ops_def_from_json_file(json_file_path))
    return ret
