# Copyright 2025 Huawei Technologies Co., Ltd
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Utility functions for loading ops definitions from JSON files."""

import json
import os
import glob
from typing import Dict, List, Any, Tuple


def _parse_optional_mapping(json_data: Dict[str, Any]) -> Dict[str, str]:
    """
    Parse MrtOptional fields from JSON data and build anonymous -> baseType.def mapping.

    Args:
        json_data: The JSON data loaded from json

    Returns:
        A dictionary mapping anonymous type names to their baseType.def values.
    """
    optional_mapping = {}
    optional_list = json_data.get('!instanceof', {}).get('MrtOptional', [])
    for anonymous_name in optional_list:
        if anonymous_name in json_data:
            anonymous_def = json_data[anonymous_name]
            base_type = anonymous_def.get('baseType', {}).get('def')
            if base_type:
                optional_mapping[anonymous_name] = base_type
    return optional_mapping


def _parse_ioref_config(gen_acl_cfg: Dict[str, Any]) -> List[tuple[int, int]]:
    """
    Parse IORef configuration from genAclnnCfg.

    Args:
        gen_acl_cfg: The genAclnnCfg dictionary from JSON

    Returns:
        A list of tuples (output_index, input_index) representing IORef pairs.
    """
    if gen_acl_cfg is None:
        return []

    ioref_pairs = []
    # genAclnnCfg structure: (AclnnConfig (IORef out0, in0), (IORef out1, in1), ...)
    # The args field contains a list of IORef entries
    args = gen_acl_cfg.get('args', [])
    for arg in args:
        if arg[0] is None:
            continue
        ioref_dag = arg[0]
        if ioref_dag.get('operator', {}).get('def') == 'IORef':
            ioref_args = ioref_dag.get('args', [])
            if len(ioref_args) >= 2:
                output_idx = ioref_args[0][0]
                input_idx = ioref_args[1][0]
                ioref_pairs.append((output_idx, input_idx))
    return ioref_pairs


def _parse_ops_def(json_data: Dict[str, Any]) -> List[Dict[str, Any]]:
    """Parse the operation definitions from the JSON data."""
    ret = []
    for op in json_data['!instanceof']['Op']:
        ori_op_def = json_data[op]
        # Skip if genAclnnOp is null or not present
        gen_acl_op = ori_op_def.get('genAclnnOp')
        if not gen_acl_op:
            continue
        # Parse IORef configuration
        gen_acl_cfg = ori_op_def.get('genAclnnCfg')
        ioref_pairs = _parse_ioref_config(gen_acl_cfg)
        # Build op definition with genAclnnOp, arguments, results, and IORef pairs
        op_def = {
            'opName': ori_op_def['opName'],
            'genAclnnOp': gen_acl_op,
            'arguments': ori_op_def['arguments'],
            'results': ori_op_def['results'],
            'iorefPairs': ioref_pairs,
        }
        ret.append(op_def)
    return ret

def load_ops_def_from_json_file(json_file_path: str) -> Tuple[List[Dict[str, Any]], Dict[str, str]]:
    """
    Load the json file which is generated by llvm-tblgen and extract the operation definitions from it.

    Args:
        json_file_path: Path to the JSON file.

    Returns:
        A tuple of (List of dictionaries, each dictionary is an operation definition,
                   Optional mapping dictionary from anonymous to baseType.def)
    """
    print(f"Loading the JSON file: {json_file_path}")
    if not os.path.exists(json_file_path):
        raise FileNotFoundError(f"JSON file not found: {json_file_path},\
        make sure you have run the llvm-tblgen to generate the JSON file.")

    with open(json_file_path, 'r', encoding='utf-8') as f:
        json_data = json.load(f)

    # Dump the JSON data as a readable JSON file for debugging and verification
    # Rewrite the original JSON file with a readable format (with indentation)
    with open(json_file_path, "w", encoding="utf-8") as f:
        json.dump(json_data, f, ensure_ascii=False, indent=4)
    print(f"Dumped readable Mrt Dialect JSON to: {json_file_path}")

    ops_def = _parse_ops_def(json_data)
    optional_mapping = _parse_optional_mapping(json_data)
    return ops_def, optional_mapping

def load_ops_def_from_json_files(json_file_dir: str) -> Tuple[List[List[Dict[str, Any]]], Dict[str, str]]:
    """
    Load ops def from multiple json files.

    Args:
        json_file_dir: Directory path to the json files.

    Returns:
        A tuple of (List of lists, each list is a set of operation definitions,
                   Optional mapping dictionary from anonymous to baseType.def)
    """
    ret = []
    optional_mapping = {}
    json_file_paths = glob.glob(os.path.join(json_file_dir, '*.json'))
    if not json_file_paths:
        raise FileNotFoundError(f"No json files found in directory: {json_file_dir}")
    for json_file_path in json_file_paths:
        ops_def, mapping = load_ops_def_from_json_file(json_file_path)
        ret.append(ops_def)
        optional_mapping.update(mapping)
    return ret, optional_mapping
